# Generated by Django 3.1.6 on 2021-03-11 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта',
                'verbose_name_plural': 'Типы контактов',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('appeal', models.CharField(default='г-н', max_length=30, verbose_name='Обращение')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('requisites', models.TextField(max_length=500, verbose_name='Реквизиты')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагент',
            },
        ),
        migrations.CreateModel(
            name='ContractorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус контрагентов',
                'verbose_name_plural': 'Статусы контрагентов',
            },
        ),
        migrations.CreateModel(
            name='FieldOfActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='TypeOfContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип контрагентов',
                'verbose_name_plural': 'Типы контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
                ('contact_name', models.CharField(max_length=90, verbose_name='Имя контакта')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Контрагент')),
                ('type_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт контрагента',
                'verbose_name_plural': 'Контакты контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Контрагент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к контрагенту',
                'verbose_name_plural': 'Комментарии к контрагенту',
            },
        ),
        migrations.AddField(
            model_name='contractor',
            name='field_of_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.fieldofactivity', verbose_name='Сфера деятельности'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.contractorstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='type_of_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.typeofcontractor', verbose_name='Тип контрагента'),
        ),
    ]
