# Generated by Django 3.1.6 on 2021-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0002_auto_20210317_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='appeal_en',
            field=models.CharField(default='Mr.', max_length=30, verbose_name='Обращение(англ)'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='position_en',
            field=models.CharField(blank=True, max_length=30, verbose_name='Должность(англ)'),
        ),
    ]
