# Generated by Django 3.1.6 on 2021-04-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0003_auto_20210401_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
            ],
            options={
                'verbose_name': 'Контакт контрагента',
                'verbose_name_plural': 'Контакты контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Контрагент')),
            ],
        ),
        migrations.DeleteModel(
            name='ContractorContact',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.contactperson', verbose_name='Контактое лицо'),
        ),
        migrations.AddField(
            model_name='contact',
            name='type_of_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contacttype', verbose_name='Вид контакта'),
        ),
    ]
