# Generated by Django 3.1.6 on 2021-04-11 16:00

import app_organizations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0007_auto_20210410_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorFileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, verbose_name='Наимнование для образования ссылки(англ)')),
            ],
            options={
                'verbose_name': 'Категория файлов контрагента',
                'verbose_name_plural': 'Категории файлов контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(max_length=500, upload_to=app_organizations.models.UploadToPathAndRename('C:\\Users\\kvalj\\PycharmProjects\\django_firm_manager\\firmmanager\\media/app_organizations\\organization_files'), verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractorfilecategory', verbose_name='Категория')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Файл контрагента',
                'verbose_name_plural': 'Файлы контрагентов',
            },
        ),
    ]
