# Generated by Django 3.1.6 on 2021-04-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0008_contractorfile_contractorfilecategory'),
        ('app_crm', '0003_auto_20210401_0812'),
    ]

    operations = [
    ]
