# Generated by Django 3.1.6 on 2021-05-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0015_auto_20210517_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
