# Generated by Django 3.1.6 on 2021-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0019_auto_20210529_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadcontactperson',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
