# Generated by Django 3.1.6 on 2021-05-30 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0020_auto_20210530_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorcontactperson',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='contractorcontactperson',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='contractorcontactperson',
            name='department_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='contractorcontactperson',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='contractorcontactperson',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='contractorcontactperson',
            name='serial_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия'),
        ),
    ]
