# Generated by Django 3.1.6 on 2021-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0022_auto_20210601_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='requisites',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Реквизиты'),
        ),
    ]
