# Generated by Django 3.2.4 on 2021-06-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0024_contractorrequisites_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrequisites',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_requisites', to='app_crm.contractor', verbose_name='Контрагент'),
        ),
    ]
