# Generated by Django 3.2.4 on 2021-07-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0026_alter_contractorrequisites_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта лида',
                'verbose_name_plural': 'Типы контактов лидов',
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.lead', verbose_name='Лид')),
                ('type_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.leadcontacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт лида',
                'verbose_name_plural': 'Контакты лидов',
            },
        ),
    ]
