# Generated by Django 3.2.4 on 2021-07-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0029_auto_20210705_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта контрагента',
                'verbose_name_plural': 'Типы контактов контрагента',
            },
        ),
        migrations.CreateModel(
            name='ContractorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактные данные')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors_contacts', related_query_name='contractor_contacts', to='app_crm.contractor', verbose_name='Контрагент')),
                ('type_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractorcontacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт контрагента',
                'verbose_name_plural': 'Контакты контрагентов',
            },
        ),
    ]
