# Generated by Django 3.2.4 on 2021-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0031_auto_20210711_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorcontactperson',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
