# Generated by Django 3.2.4 on 2021-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0032_alter_contractorcontactperson_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='work_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Рабочее наименование'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Юр. наименование'),
        ),
    ]
