# Generated by Django 3.1.6 on 2021-03-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0002_auto_20210316_2102'),
        ('app_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstorebooking',
            name='specification',
        ),
        migrations.AddField(
            model_name='productstorebooking',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_documents.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
