# Generated by Django 3.1.6 on 2021-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0002_auto_20210316_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=800, verbose_name='Описание'),
        ),
    ]
