# Generated by Django 3.1.6 on 2021-04-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0014_auto_20210416_1118'),
        ('app_storage', '0005_auto_20210416_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductStoreSpecificationBooking',
            new_name='ProductStoreOrderBooking',
        ),
    ]
