# Generated by Django 3.1.6 on 2021-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0006_auto_20210416_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoreorderbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Цена за ед.'),
        ),
    ]
