# Generated by Django 3.1.6 on 2021-04-17 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_storage', '0008_auto_20210417_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoreincome',
            name='responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productstoreoutcome',
            name='responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productstoreincome',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата прихода'),
        ),
    ]
