# Generated by Django 3.1.6 on 2021-05-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0019_auto_20210529_1628'),
        ('app_storage', '0012_auto_20210503_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstoreorderbooking',
            options={'verbose_name': 'Бронь продукции по заказу', 'verbose_name_plural': 'Брони продукции по заказам'},
        ),
        migrations.CreateModel(
            name='ProductStoreOrderWithoutContractBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Итоговая цена')),
                ('standard_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Стандартная цена')),
                ('counted_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Расчетная сумма')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Итоговая сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.orderwithoutcontract', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Бронь продукции по заказу без договора',
                'verbose_name_plural': 'Брони продукции по заказам без договора',
            },
        ),
    ]
