# Generated by Django 3.2.4 on 2021-06-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0019_auto_20210529_1628'),
        ('app_storage', '0014_alter_productstoreoutcome_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_bookings', related_query_name='order_bookings', to='app_documents.order', verbose_name='Заказ'),
        ),
    ]
