# Generated by Django 3.1.6 on 2021-03-11 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_crm', '0001_initial'),
        ('app_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер договора')),
                ('created', models.DateField(auto_now_add=True)),
                ('delivery_address', models.CharField(max_length=50, verbose_name='Место поставки')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Стоимость к 1 рублю')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('delivery_time', models.IntegerField(default=datetime.datetime(2021, 1, 1, 0, 0), verbose_name='Срок поставки')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Условие поставки',
                'verbose_name_plural': 'Условия поставки',
            },
        ),
        migrations.CreateModel(
            name='PaymentConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Условие оплаты',
                'verbose_name_plural': 'Условия оплаты',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Номер спецификации')),
                ('created', models.DateField(auto_now_add=True)),
                ('loading_place', models.CharField(max_length=100, verbose_name='Место загрузки')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.contract', verbose_name='Договор')),
                ('delivery_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.deliveryconditions', verbose_name='Условия поставки')),
                ('payment_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.paymentconditions', verbose_name='Условия оплаты')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Номер')),
                ('created', models.DateField(auto_now_add=True)),
                ('shipment_mark', models.CharField(max_length=100, verbose_name='Отгрузочная метка')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.specification', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация поставщик'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.contracttype', verbose_name='Тип договора'),
        ),
    ]
