# Generated by Django 3.2.6 on 2021-09-09 14:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер договора')),
                ('created', models.DateField(verbose_name='Дата создания')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('char_code', models.CharField(max_length=10, verbose_name='Символьное обозначение')),
                ('nominal', models.IntegerField(verbose_name='Номинал')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Условие поставки',
                'verbose_name_plural': 'Условия поставки',
            },
        ),
        migrations.CreateModel(
            name='PaymentConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('description_en', models.CharField(blank=True, max_length=1000, verbose_name='Описание(англ)')),
            ],
            options={
                'verbose_name': 'Условие оплаты',
                'verbose_name_plural': 'Условия оплаты',
            },
        ),
        migrations.CreateModel(
            name='ShipmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=1000, verbose_name='Описание(англ)')),
            ],
            options={
                'verbose_name': 'Отгрузочная метка',
                'verbose_name_plural': 'Отгрузочные метки',
            },
        ),
        migrations.CreateModel(
            name='OrderWithoutContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='auto', max_length=30, verbose_name='Номер заказа')),
                ('created', models.DateField(auto_now_add=True)),
                ('delivery_time', models.IntegerField(default=1, verbose_name='Срок поставки, дней')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Место поставки')),
                ('counted_sum', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Расчетная сумма')),
                ('total_sum', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Итоговая сумма')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Клиент')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.currency', verbose_name='Валюта')),
                ('delivery_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.deliveryconditions', verbose_name='Условия поставки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация поставщик')),
                ('payment_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.paymentconditions', verbose_name='Условия оплаты')),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipment_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shipmentmark', verbose_name='Отгрузочная метка')),
            ],
            options={
                'verbose_name': 'Заказ без договора',
                'verbose_name_plural': 'Заказы без договора',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='auto', max_length=30, verbose_name='Номер заказа')),
                ('created', models.DateField(auto_now_add=True)),
                ('delivery_time', models.IntegerField(default=1, verbose_name='Срок поставки, дней')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Место поставки')),
                ('counted_sum', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='Расчетная сумма')),
                ('currency_counted_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Расчетная сумма в валюте')),
                ('total_sum', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='Итоговая сумма')),
                ('currency_total_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Итоговая сумма в валюте')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_documents.contract', verbose_name='Договор')),
                ('delivery_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.deliveryconditions', verbose_name='Условия поставки')),
                ('payment_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.paymentconditions', verbose_name='Условия оплаты')),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipment_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shipmentmark', verbose_name='Отгрузочная метка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация поставщик'),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.contracttype', verbose_name='Тип договора'),
        ),
    ]
