# Generated by Django 3.1.6 on 2021-03-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0007_auto_20210321_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryconditions',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(default=1, verbose_name='Срок поставки'),
        ),
    ]
