# Generated by Django 3.1.6 on 2021-04-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0012_auto_20210410_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
