# Generated by Django 3.1.6 on 2021-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0013_auto_20210410_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counted_sum',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Расчетная сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Итоговая сумма'),
        ),
    ]
