# Generated by Django 3.1.6 on 2021-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0014_auto_20210416_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconditions',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание(англ)'),
        ),
        migrations.AlterField(
            model_name='paymentconditions',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
    ]
