# Generated by Django 3.1.6 on 2021-05-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_crm', '0012_auto_20210515_1336'),
        ('app_organizations', '0013_workercontact_workercontacttype'),
        ('app_documents', '0016_auto_20210425_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWithoutContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Номер заказа')),
                ('created', models.DateField(auto_now_add=True)),
                ('delivery_time', models.IntegerField(default=1, verbose_name='Срок поставки, дней')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Место поставки')),
                ('counted_sum', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Расчетная сумма')),
                ('total_sum', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Итоговая сумма')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Клиент')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.currency', verbose_name='Валюта')),
                ('delivery_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.deliveryconditions', verbose_name='Условия поставки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация поставщик')),
                ('payment_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.paymentconditions', verbose_name='Условия оплаты')),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipment_mark', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shipmentmark', verbose_name='Отгрузочная метка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
