# Generated by Django 3.1.6 on 2021-05-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0017_orderwithoutcontract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderwithoutcontract',
            options={'verbose_name': 'Заказ без договора', 'verbose_name_plural': 'Заказы без договора'},
        ),
    ]
