# Generated by Django 3.1.6 on 2021-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Номер заказа')),
                ('created', models.DateField(auto_now_add=True)),
                ('loading_place', models.CharField(max_length=100, verbose_name='Место загрузки')),
                ('shipment_mark', models.CharField(max_length=100, verbose_name='Отгрузочная метка')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.RemoveField(
            model_name='specification',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='delivery_conditions',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='payment_conditions',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
