# Generated by Django 3.1.6 on 2021-03-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0002_auto_20210316_2102'),
        ('app_storage', '0002_auto_20210316_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.deliveryconditions', verbose_name='Условия поставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.paymentconditions', verbose_name='Условия оплаты'),
        ),
    ]
