# Generated by Django 3.1.6 on 2021-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0003_auto_20210316_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='char_code',
            field=models.CharField(default='RUB', max_length=10, verbose_name='Символьное обозначение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='001', max_length=20, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='nominal',
            field=models.IntegerField(default=1, verbose_name='Номинал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Цена'),
        ),
    ]
