# Generated by Django 3.1.6 on 2021-03-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0004_auto_20210321_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
