# Generated by Django 3.1.6 on 2021-03-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0005_auto_20210321_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='total_sum',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
