# Generated by Django 3.1.6 on 2021-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0006_contract_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='total_sum',
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
