# Generated by Django 3.1.6 on 2021-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0008_auto_20210328_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(default=1, verbose_name='Срок поставки, дней'),
        ),
    ]
