# Generated by Django 3.1.6 on 2021-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0010_auto_20210406_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loading_place',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Нет адреса', max_length=150, verbose_name='Место поставки'),
            preserve_default=False,
        ),
    ]
