# Generated by Django 3.1.6 on 2021-04-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0015_auto_20210420_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=1000, verbose_name='Описание(англ)')),
            ],
            options={
                'verbose_name': 'Отгрузочная метка',
                'verbose_name_plural': 'Отгрузочные метки',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_mark',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shipmentmark', verbose_name='Отгрузочная метка'),
        ),
    ]
