# Generated by Django 3.1.6 on 2021-05-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0018_auto_20210520_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shipmentmark', verbose_name='Отгрузочная метка'),
        ),
        migrations.AlterField(
            model_name='orderwithoutcontract',
            name='shipment_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shipmentmark', verbose_name='Отгрузочная метка'),
        ),
    ]
