# Generated by Django 3.2.4 on 2021-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0019_auto_20210529_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_counted_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Расчетная сумма в валюте'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Итоговая сумма в валюте'),
        ),
    ]
