# Generated by Django 3.2.6 on 2021-09-09 14:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(verbose_name='Количество позиций')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Итоговая сумма')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='PackageInsideType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид внутренней упаковки',
                'verbose_name_plural': 'Виды внутренней упаковки',
            },
        ),
        migrations.CreateModel(
            name='PackageOutsideType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид внешней упаковки',
                'verbose_name_plural': 'Виды внешней упаковки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Артикул')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('size', models.CharField(max_length=30, verbose_name='Размер')),
                ('version', models.CharField(max_length=30, verbose_name='Версия')),
                ('materials', models.CharField(max_length=100, verbose_name='Материалы')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за 1 ед. в рублях')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, max_length=1000, verbose_name='Описание(англ)')),
                ('packing_inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.packageinsidetype', verbose_name='Внутренняя упаковка')),
                ('packing_outside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.packageoutsidetype', verbose_name='Внешнняя упаковка')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='ProductStoreOutcomeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина выпуска продукции',
                'verbose_name_plural': 'Причины выпуска продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип продукции',
                'verbose_name_plural': 'Типы продукции',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='ProductStoreOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_storage.productstoreoutcomereason', verbose_name='Причина выпуска')),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Списание продукции со склада',
                'verbose_name_plural': 'Списания продукции со складов',
            },
        ),
        migrations.CreateModel(
            name='ProductStoreOrderWCBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая цена')),
                ('standard_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Стандартная цена')),
                ('counted_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Расчетная сумма')),
                ('total_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_documents.orderwithoutcontract', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Бронь продукции по заказу без договора',
                'verbose_name_plural': 'Брони продукции по заказам без договора',
            },
        ),
        migrations.CreateModel(
            name='ProductStoreOrderBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая цена')),
                ('standard_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Стандартная цена')),
                ('counted_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Расчетная сумма')),
                ('total_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_documents.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Бронь продукции по заказу',
                'verbose_name_plural': 'Брони продукции по заказам',
            },
        ),
        migrations.CreateModel(
            name='ProductStoreIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата прихода')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Приход продукции на склад',
                'verbose_name_plural': 'Приходы продукции на склад',
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('booked', models.IntegerField(verbose_name='Забронировано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Колисчество продукции на складе',
                'verbose_name_plural': 'Колисчество продукции на складах',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.producttype', verbose_name='Тип продукции'),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Продукция в корзине',
                'verbose_name_plural': 'Продукция в корзинах',
            },
        ),
    ]
