# Generated by Django 3.1.6 on 2021-03-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInsideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид внутренней упаковки',
                'verbose_name_plural': 'Виды внутренней упаковки',
            },
        ),
        migrations.CreateModel(
            name='PackageOutsideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид внешней упаковки',
                'verbose_name_plural': 'Виды внешней упаковки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Артикул')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('size', models.CharField(max_length=30, verbose_name='Размер')),
                ('version', models.CharField(max_length=30, verbose_name='Версия')),
                ('materials', models.CharField(max_length=100, verbose_name='Материалы')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за 1 ед. в рублях')),
                ('packing_inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.packageinsidetype', verbose_name='Внутренняя упаковка')),
                ('packing_outside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.packageoutsidetype', verbose_name='Внешнняя упаковка')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип продукции',
                'verbose_name_plural': 'Типы продукции',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='ProductStoreIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStoreBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сумма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.specification', verbose_name='Спецификация')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Бронь продукции по спецификации',
                'verbose_name_plural': 'Брони продукции по спецификации',
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('booked', models.IntegerField(verbose_name='Забронировано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Продукция на складе',
                'verbose_name_plural': 'Продукция на складе',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.producttype', verbose_name='Тип продукции'),
        ),
    ]
