# Generated by Django 3.2.6 on 2021-09-12 09:40

import app_storage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstore',
            options={'verbose_name': 'Количество продукции на складе', 'verbose_name_plural': 'Количество продукции на складах'},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=app_storage.models.UploadToPathAndRename('products/'), verbose_name='Изображение')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_storage.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
    ]
