# Generated by Django 3.2.6 on 2021-09-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0002_auto_20210912_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, help_text='Описание на английском языке', max_length=1000, null=True, verbose_name='Описание(англ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_outside',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.packageoutsidetype', verbose_name='Внешняя упаковка'),
        ),
    ]
