# Generated by Django 3.1.6 on 2021-04-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0003_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstoreincome',
            options={'verbose_name': 'Приход продукции на склад', 'verbose_name_plural': 'Приходы продукции на склад'},
        ),
    ]
