# Generated by Django 3.2.6 on 2021-09-12 11:04

import app_storage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0003_auto_20210912_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=app_storage.models.UploadToPathAndRename('app_storage/products/'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_storage.product', verbose_name='Товар'),
        ),
    ]
