# Generated by Django 3.1.6 on 2021-04-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0013_auto_20210410_1601'),
        ('app_storage', '0004_auto_20210406_2334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductStoreBooking',
            new_name='ProductStoreSpecificationBooking',
        ),
        migrations.AlterModelOptions(
            name='productstore',
            options={'verbose_name': 'Колисчество продукции на складе', 'verbose_name_plural': 'Колисчество продукции на складах'},
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание(англ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='ProductStoreOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Списание продукции со склада',
                'verbose_name_plural': 'Списания продукции со складов',
            },
        ),
    ]
