# Generated by Django 3.1.6 on 2021-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0007_productstoreorderbooking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstoreorderbooking',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='productstoreorderbooking',
            name='sum',
        ),
        migrations.AddField(
            model_name='productstoreorderbooking',
            name='counted_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Расчетная сумма'),
        ),
        migrations.AddField(
            model_name='productstoreorderbooking',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Итоговая сумма'),
        ),
    ]
