# Generated by Django 3.1.6 on 2021-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0010_auto_20210420_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Итоговая цена'),
        ),
    ]
