# Generated by Django 3.2.4 on 2021-06-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0019_auto_20210529_1628'),
        ('app_storage', '0015_alter_productstoreorderbooking_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductStoreOrderWithoutContractBooking',
            new_name='ProductStoreOrderWCBooking',
        ),
    ]
