# Generated by Django 3.2.6 on 2021-08-16 13:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0021_auto_20210816_1638'),
        ('app_storage', '0016_rename_productstoreorderwithoutcontractbooking_productstoreorderwcbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinsidetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packageoutsidetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstoreincome',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='counted_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Расчетная сумма'),
        ),
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_documents.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Стандартная цена'),
        ),
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='productstoreorderbooking',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='productstoreorderwcbooking',
            name='counted_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Расчетная сумма'),
        ),
        migrations.AlterField(
            model_name='productstoreorderwcbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstoreorderwcbooking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_documents.orderwithoutcontract', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productstoreorderwcbooking',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Стандартная цена'),
        ),
        migrations.AlterField(
            model_name='productstoreorderwcbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='productstoreorderwcbooking',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='productstoreoutcome',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstoreoutcomereason',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
