# Generated by Django 3.1.6 on 2021-03-11 18:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('tin', models.CharField(max_length=12, verbose_name='ИНН(TIN)')),
                ('pprnie', models.CharField(max_length=15, verbose_name='ОГРИП(PPRNIE)')),
                ('registration', models.CharField(max_length=100, verbose_name='Уведомление о постановке на учет')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('serial_number', models.CharField(blank=True, max_length=4, verbose_name='Серия')),
                ('number', models.CharField(blank=True, max_length=6, verbose_name='Номер')),
                ('issued_by', models.CharField(blank=True, max_length=100, verbose_name='Кем выдан')),
                ('date', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Дата выдачи')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Дата рождения')),
                ('department_code', models.CharField(blank=True, max_length=20, verbose_name='Код подразделения')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('short_code', models.CharField(max_length=30, verbose_name='Кодовое обозначение(SWIFT)')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('payment_account', models.CharField(max_length=30, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(blank=True, max_length=30, verbose_name='Корреспондентный счет')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
    ]
