# Generated by Django 3.1.6 on 2021-03-17 19:53

import app_organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to=app_organizations.models.UploadToPathAndRename('C:\\Users\\kvalj\\PycharmProjects\\django_firm_manager\\firmmanager\\media/app_organizations\\organization_files'), verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
