# Generated by Django 3.1.6 on 2021-03-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0003_auto_20210317_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationfile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
