# Generated by Django 3.1.6 on 2021-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0005_auto_20210327_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='appeal_en',
            field=models.CharField(blank=True, default='Mr.', max_length=30, verbose_name='Обращение(англ)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='position',
            field=models.CharField(blank=True, max_length=30, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='organization',
            name='position_en',
            field=models.CharField(blank=True, max_length=30, verbose_name='Должность(англ)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='appeal',
            field=models.CharField(blank=True, default='г-н', max_length=30, verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Действующий на основании'),
        ),
    ]
