# Generated by Django 3.1.6 on 2021-03-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0006_auto_20210327_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='pprnie',
            field=models.CharField(max_length=15, verbose_name='ОГРН(ИП)'),
        ),
    ]
