# Generated by Django 3.1.6 on 2021-04-01 19:08

import app_organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0008_auto_20210401_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=app_organizations.models.UploadToPathAndRename('C:\\Users\\kvalj\\PycharmProjects\\django_firm_manager\\firmmanager\\media/app_organizations\\organization_files'), verbose_name='Файл'),
        ),
    ]
