# Generated by Django 3.1.6 on 2021-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0009_auto_20210401_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_address_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Юр. адрес(англ)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Действующий на основании(англ)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование(англ)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='requisites_en',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Банковские реквизиты(англ)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
