# Generated by Django 3.1.6 on 2021-05-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0011_auto_20210411_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация'),
        ),
    ]
