# Generated by Django 3.1.6 on 2021-05-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0012_auto_20210503_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта',
                'verbose_name_plural': 'Типы контактов',
            },
        ),
        migrations.CreateModel(
            name='WorkerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
                ('type_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.workercontacttype', verbose_name='Тип контакта')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Контакт сотрудника',
                'verbose_name_plural': 'Контакты сотрудников',
            },
        ),
    ]
