# Generated by Django 3.1.6 on 2021-05-15 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0013_workercontact_workercontacttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация'),
        ),
    ]
