# Generated by Django 3.2.6 on 2021-08-16 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_storage', '0017_auto_20210816_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(verbose_name='Количество позиций')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Итоговая сумма')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_storage.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Продукция в корзине',
                'verbose_name_plural': 'Продукция в корзинах',
            },
        ),
    ]
