# Generated by Django 3.2.6 on 2021-09-19 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_storage', '0004_auto_20210912_1404'),
        ('app_organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_crm', '0001_initial'),
        ('app_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Дата и время создания')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=4000, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('tags', models.CharField(max_length=200, verbose_name='Тэги')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Постановщик')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
            },
        ),
        migrations.CreateModel(
            name='TaskResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_users.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Исполнитель задачи',
                'verbose_name_plural': 'Исполнители задач',
            },
        ),
        migrations.CreateModel(
            name='TaskRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_documents.contract', verbose_name='Договор')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_crm.contractor', verbose_name='Контрагент')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_crm.lead', verbose_name='Лид')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_documents.order', verbose_name='Заказ')),
                ('order_wc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_documents.orderwithoutcontract', verbose_name='Заказ без договора')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_organizations.organization', verbose_name='Организация')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_storage.product', verbose_name='Продукция')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_storage.store', verbose_name='Склад')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_references', to='app_users.task', verbose_name='Задача')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_references', to='app_organizations.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ссылка задачи',
                'verbose_name_plural': 'Ссылки задач',
            },
        ),
        migrations.CreateModel(
            name='TaskCoexecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coexecutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соисполнитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Соисполнитель задачи',
                'verbose_name_plural': 'Соисполнители задач',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.taskstatus', verbose_name='Статус задачи'),
        ),
    ]
