# Generated by Django 3.2.6 on 2021-09-09 14:09

import app_organizations.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Наименование(англ)')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='Должность')),
                ('position_en', models.CharField(blank=True, max_length=30, verbose_name='Должность(англ)')),
                ('appeal', models.CharField(blank=True, default='г-н', max_length=30, verbose_name='Обращение')),
                ('appeal_en', models.CharField(blank=True, default='Mr.', max_length=30, verbose_name='Обращение(англ)')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('name_en', models.CharField(blank=True, max_length=30, verbose_name='Имя(Англ)')),
                ('second_name_en', models.CharField(blank=True, max_length=30, verbose_name='Отчество(Англ)')),
                ('last_name_en', models.CharField(blank=True, max_length=30, verbose_name='Фамилия(Англ)')),
                ('legal_address', models.CharField(max_length=200, verbose_name='Юр. адрес')),
                ('legal_address_en', models.CharField(blank=True, max_length=200, verbose_name='Юр. адрес(англ)')),
                ('actual_address', models.CharField(blank=True, max_length=200, verbose_name='Фактический адрес')),
                ('tin', models.CharField(max_length=12, verbose_name='ИНН(TIN)')),
                ('kpp', models.CharField(max_length=12, verbose_name='КПП')),
                ('pprnie', models.CharField(max_length=15, verbose_name='ОГРН(ИП)')),
                ('registration', models.CharField(blank=True, max_length=100, verbose_name='Действующий на основании')),
                ('registration_en', models.CharField(blank=True, max_length=100, verbose_name='Действующий на основании(англ)')),
                ('requisites', models.TextField(max_length=1000, verbose_name='Банковские реквизиты')),
                ('requisites_en', models.TextField(blank=True, max_length=1000, verbose_name='Банковские реквизиты(англ)')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('serial_number', models.CharField(blank=True, max_length=4, verbose_name='Серия')),
                ('number', models.CharField(blank=True, max_length=6, verbose_name='Номер')),
                ('issued_by', models.CharField(blank=True, max_length=100, verbose_name='Кем выдан')),
                ('date', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата выдачи')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата рождения')),
                ('department_code', models.CharField(blank=True, max_length=20, verbose_name='Код подразделения')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='WorkerContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта',
                'verbose_name_plural': 'Типы контактов',
            },
        ),
        migrations.CreateModel(
            name='WorkerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
                ('type_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.workercontacttype', verbose_name='Тип контакта')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Контакт сотрудника',
                'verbose_name_plural': 'Контакты сотрудников',
            },
        ),
        migrations.CreateModel(
            name='OrganizationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(max_length=500, upload_to=app_organizations.models.UploadToPathAndRename('C:\\Users\\kvalj\\PycharmProjects\\django_firm_manager\\media/app_organizations\\organization_files'), verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
