# Generated by Django 3.1.6 on 2021-03-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0004_organizationfile_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='actual_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='appeal',
            field=models.CharField(default='г-н', max_length=30, verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_name',
            field=models.CharField(default='Геркен', max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address',
            field=models.CharField(default='Some address', max_length=200, verbose_name='Юр. адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Павел', max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='requisites',
            field=models.TextField(default='Реквизиты', max_length=1000, verbose_name='Банковские реквизиты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='requisites_en',
            field=models.TextField(default='Реквизиты на английском', max_length=1000, verbose_name='Банковские реквизиты(англ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
