# Generated by Django 3.1.6 on 2021-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0010_auto_20210410_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия(Англ)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя(Англ)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='second_name_en',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество(Англ)'),
        ),
    ]
