# Generated by Django 3.2.6 on 2021-08-16 13:38

import app_organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0015_organization_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=app_organizations.models.UploadToPathAndRename('C:\\Users\\kvalj\\PycharmProjects\\django_firm_manager\\media/app_organizations\\organization_files'), verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='organizationfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workercontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workercontacttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
