# Generated by Django 3.2.6 on 2021-09-09 14:09

import app_organizations.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPersonContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта контактного лица',
                'verbose_name_plural': 'Типы контактов контактных лиц',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Юр. наименование')),
                ('work_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Рабочее наименование')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('position_en', models.CharField(blank=True, max_length=30, verbose_name='Должность(англ)')),
                ('appeal', models.CharField(default='г-н', max_length=30, verbose_name='Обращение')),
                ('appeal_en', models.CharField(blank=True, default='Mr.', max_length=30, null=True, verbose_name='Обращение(англ)')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('tel', models.CharField(max_length=20, verbose_name='Основной номер телефона')),
                ('legal_address', models.CharField(max_length=200, verbose_name='Юр. адрес')),
                ('actual_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фактический адрес')),
                ('requisites', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Реквизиты')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='ContractorContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги')),
                ('serial_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия')),
                ('number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер')),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан')),
                ('date', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата выдачи')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Дата рождения')),
                ('department_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код подразделения')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='app_crm.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Контактное лицо контрагента',
                'verbose_name_plural': 'Контактные лица контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта контрагента',
                'verbose_name_plural': 'Типы контактов контрагента',
            },
        ),
        migrations.CreateModel(
            name='ContractorFileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, verbose_name='Наимнование для образования ссылки(англ)')),
            ],
            options={
                'verbose_name': 'Категория файлов контрагента',
                'verbose_name_plural': 'Категории файлов контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус контрагентов',
                'verbose_name_plural': 'Статусы контрагентов',
            },
        ),
        migrations.CreateModel(
            name='FieldOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('purpose', models.CharField(max_length=1000, verbose_name='Цель сотрудничества')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('field_of_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.fieldofactivity', verbose_name='Сфера деятельности')),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='LeadContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Контактное лицо лида',
                'verbose_name_plural': 'Контактные лица лидов',
            },
        ),
        migrations.CreateModel(
            name='LeadContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип контакта лида',
                'verbose_name_plural': 'Типы контактов лидов',
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус лида',
                'verbose_name_plural': 'Статусы лидов',
            },
        ),
        migrations.CreateModel(
            name='TypeOfContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип контрагентов',
                'verbose_name_plural': 'Типы контрагентов',
            },
        ),
        migrations.CreateModel(
            name='LeadContactPersonContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.leadcontactperson', verbose_name='Контактое лицо')),
                ('type_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contactpersoncontacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт контактного лица лида',
                'verbose_name_plural': 'Контакты контактных лиц лидов',
            },
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактные данные')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_contacts', related_query_name='lead_contacts', to='app_crm.lead', verbose_name='Лид')),
                ('type_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.leadcontacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт лида',
                'verbose_name_plural': 'Контакты лидов',
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.lead', verbose_name='Лид')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к лиду',
                'verbose_name_plural': 'Комментарии к лидам',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.leadstatus', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ContractorRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=50, verbose_name='Сокр. наименование')),
                ('mailing_address', models.CharField(max_length=200, verbose_name='Почтовый адрес')),
                ('tin', models.CharField(max_length=12, verbose_name='ИНН(TIN)')),
                ('kpp', models.CharField(max_length=12, verbose_name='КПП')),
                ('pprnie', models.CharField(max_length=15, verbose_name='ОГРН(ИП)')),
                ('checking_account', models.CharField(max_length=24, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(max_length=24, verbose_name='Корреспондентский счет')),
                ('bank_bik', models.CharField(max_length=9, verbose_name='БИК Банка')),
                ('bank_title', models.CharField(max_length=200, verbose_name='Банк')),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='russian_requisites', to='app_crm.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Реквизиты контрагента',
                'verbose_name_plural': 'Реквизиты контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(max_length=500, upload_to=app_organizations.models.UploadToPathAndRename('C:\\Users\\kvalj\\PycharmProjects\\django_firm_manager\\media/app_organizations\\organization_files'), verbose_name='Файл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractorfilecategory', verbose_name='Категория')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Файл контрагента',
                'verbose_name_plural': 'Файлы контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorContactPersonContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app_crm.contractorcontactperson', verbose_name='Контактое лицо')),
                ('type_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contactpersoncontacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт контактного лица контрагента',
                'verbose_name_plural': 'Контакты контактных лиц контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактные данные')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors_contacts', related_query_name='contractor_contacts', to='app_crm.contractor', verbose_name='Контрагент')),
                ('type_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractorcontacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт контрагента',
                'verbose_name_plural': 'Контакты контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ContractorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_crm.contractor', verbose_name='Контрагент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к контрагенту',
                'verbose_name_plural': 'Комментарии к контрагенту',
            },
        ),
        migrations.AddField(
            model_name='contractor',
            name='field_of_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.fieldofactivity', verbose_name='Сфера деятельности'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.contractorstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='type_of_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crm.typeofcontractor', verbose_name='Тип контрагента'),
        ),
    ]
