# Generated by Django 3.1.6 on 2021-03-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='actual_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='legal_address',
            field=models.CharField(default='Не указан', max_length=200, verbose_name='Юр. адрес'),
            preserve_default=False,
        ),
    ]
