# Generated by Django 3.1.6 on 2021-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0004_auto_20210401_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт контактного лица', 'verbose_name_plural': 'Контакты контактных лиц'},
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактные лица'},
        ),
        migrations.AddField(
            model_name='contactperson',
            name='to_delete',
            field=models.BooleanField(default=False, verbose_name='К удалению'),
        ),
    ]
