# Generated by Django 3.1.6 on 2021-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0006_contractor_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='appeal_en',
            field=models.CharField(blank=True, default='Mr.', max_length=30, verbose_name='Обращение(англ)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='requisites',
            field=models.TextField(max_length=1000, verbose_name='Реквизиты'),
        ),
    ]
