# Generated by Django 3.1.6 on 2021-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0008_contractorfile_contractorfilecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='tel',
            field=models.CharField(default='89888980008', max_length=20, verbose_name='Основной номер телефона'),
            preserve_default=False,
        ),
    ]
