# Generated by Django 3.1.6 on 2021-04-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0009_merge_20210411_1624'),
        ('app_crm', '0009_contractor_tel'),
    ]

    operations = [
    ]
