# Generated by Django 3.1.6 on 2021-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0010_merge_20210424_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='appeal_en',
            field=models.CharField(blank=True, default='Mr.', max_length=30, verbose_name='Обращение(англ)'),
        ),
    ]
