# Generated by Django 3.1.6 on 2021-05-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0011_auto_20210425_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactType',
            new_name='ContactPersonContactType',
        ),
    ]
