# Generated by Django 3.1.6 on 2021-05-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0012_auto_20210515_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContractorContact',
        ),
    ]
