# Generated by Django 3.1.6 on 2021-05-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0013_auto_20210515_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='tags',
            field=models.CharField(default='', max_length=1000, verbose_name='Теги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='tags',
            field=models.CharField(default='', max_length=1000, verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
