# Generated by Django 3.1.6 on 2021-05-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0014_auto_20210517_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='tags',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='tag',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='tag',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги'),
        ),
    ]
