# Generated by Django 3.1.6 on 2021-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0017_lead_leadstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPerson',
            new_name='ContractorContactPerson',
        ),
        migrations.AddField(
            model_name='lead',
            name='tag',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги'),
        ),
    ]
