# Generated by Django 3.1.6 on 2021-05-29 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_crm', '0018_auto_20210529_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Теги')),
                ('to_delete', models.BooleanField(default=False, verbose_name='К удалению')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Контактное лицо лида',
                'verbose_name_plural': 'Контактные лица лидов',
            },
        ),
        migrations.RenameModel(
            old_name='ContractorContact',
            new_name='ContractorContactPersonContact',
        ),
        migrations.AlterModelOptions(
            name='contractorcontactpersoncontact',
            options={'verbose_name': 'Контакт контактного лица контрагента', 'verbose_name_plural': 'Контакты контактных лиц контрагентов'},
        ),
        migrations.CreateModel(
            name='LeadContactPersonContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактные данные')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.leadcontactperson', verbose_name='Контактое лицо')),
                ('type_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contactpersoncontacttype', verbose_name='Вид контакта')),
            ],
            options={
                'verbose_name': 'Контакт контактного лица лида',
                'verbose_name_plural': 'Контакты контактных лиц лидов',
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.lead', verbose_name='Лид')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к лиду',
                'verbose_name_plural': 'Комментарии к лидам',
            },
        ),
    ]
