# Generated by Django 3.1.6 on 2021-06-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0021_auto_20210530_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='ContractorRequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=50, verbose_name='Сокр. наименование')),
                ('mailing_address', models.CharField(max_length=200, verbose_name='Почтовый адрес')),
                ('tin', models.CharField(max_length=12, verbose_name='ИНН(TIN)')),
                ('pprnie', models.CharField(max_length=15, verbose_name='ОГРН(ИП)')),
                ('checking_account', models.CharField(max_length=24, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(max_length=24, verbose_name='Корреспондентский счет')),
                ('bank_bik', models.CharField(max_length=9, verbose_name='БИК Банка')),
                ('bank_title', models.CharField(max_length=200, verbose_name='Банк')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Реквизиты контрагента',
                'verbose_name_plural': 'Реквизиты контрагентов',
            },
        ),
    ]
