# Generated by Django 3.1.6 on 2021-06-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0023_auto_20210601_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorrequisites',
            name='kpp',
            field=models.CharField(default='Не заполнен', max_length=12, verbose_name='КПП'),
            preserve_default=False,
        ),
    ]
