# Generated by Django 3.2.4 on 2021-07-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0027_auto_20210705_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorcontactperson',
            options={'verbose_name': 'Контактное лицо контрагента', 'verbose_name_plural': 'Контактные лица контрагентов'},
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='type_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.leadcontacttype', verbose_name='Вид контакта'),
        ),
    ]
