# Generated by Django 3.2.4 on 2021-07-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0028_auto_20210705_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpersoncontacttype',
            options={'verbose_name': 'Тип контакта контактного лица', 'verbose_name_plural': 'Типы контактов контактных лиц'},
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_contacts', related_query_name='lead_contacts', to='app_crm.lead', verbose_name='Лид'),
        ),
    ]
