# Generated by Django 3.2.4 on 2021-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0030_contractorcontact_contractorcontacttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='actual_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='appeal_en',
            field=models.CharField(blank=True, default='Mr.', max_length=30, null=True, verbose_name='Обращение(англ)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='contractorcontactperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contractorcontactperson',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='leadcontactperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='leadcontactperson',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность'),
        ),
    ]
